const AutogeneratedUUID4 = require('../autogeneratedUuid4');

describe('AutogeneratedUUID4 value object', () => {
  describe('when creating new UUID4', () => {
    test('when value was not provided should generate uuid4 by default', () => {
      const uuid = new AutogeneratedUUID4();

      expect(uuid.value).not.toBeUndefined();
    });

    test('when value is null and generateIfNull flag is set should generate uuid4', () => {
      const uuid = new AutogeneratedUUID4(null);

      expect(uuid.value).not.toBeUndefined();
    });
  });
});
